//===-- Ops.cpp - Cast ops verifiers -----------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#include "llzk/Dialect/Cast/IR/Ops.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Diagnostics.h"

using namespace llzk::cast;

namespace {

/// Verify the presence and basic validity of the 'overflow' attribute on the op.
/// Accepts either a StringAttr with value "trunc" or "sat", or an IntegerAttr
/// with value 0 or 1 (the enum values). For other attribute representations
/// (e.g., EnumAttr generated by TableGen) we accept them because TableGen
/// enforces the attribute type.
static ::mlir::LogicalResult verifyOverflowAttr(::mlir::Operation *op) {
  ::mlir::Attribute attr = op->getAttr("overflow");
  if (!attr) {
    return op->emitOpError() << "requires an 'overflow' attribute with value \"trunc\" or \"sat\"";
  }

  if (auto sAttr = attr.dyn_cast<::mlir::StringAttr>()) {
    llvm::StringRef v = sAttr.getValue();
    if (v != "trunc" && v != "sat") {
      return op->emitOpError() << "invalid 'overflow' attribute value '" << v
                               << "'; expected \"trunc\" or \"sat\"";
    }
  } else if (auto iAttr = attr.dyn_cast<::mlir::IntegerAttr>()) {
    int64_t val = iAttr.getValue().getSExtValue();
    if (val != 0 && val != 1) {
      return op->emitOpError() << "invalid 'overflow' enum value; expected 0 (trunc) or 1 (sat)";
    }
  }
  // If attr is an EnumAttr generated by TableGen, TableGen will ensure valid values.
  return ::mlir::success();
}

} // end anonymous namespace

::mlir::LogicalResult llzk::cast::IntToFeltOp::verify() {
  return verifyOverflowAttr(getOperation());
}

::mlir::LogicalResult llzk::cast::FeltToIndexOp::verify() {
  return verifyOverflowAttr(getOperation());
}

::mlir::LogicalResult llzk::cast::FeltToIntOp::verify() {
  return verifyOverflowAttr(getOperation());
}