name: Changelog validator
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs
      - test
      - unittests

jobs:
  call-workflow-changelog-validate:
    uses: Veridise/open-source-release-helpers/.github/workflows/changelog-validator.yml@fcc709be4a6c77a3e95ff84ec68d8c72a5e2702b
    secrets: inherit
