name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - name: GCC
            derivation: '.#debugGCC'
            report: gcc-report.xml
          - name: Clang
            derivation: '.#debugClangCov'
            report: clang-report.xml
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      # v37.1.0
      - uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.3/install
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set Git credentials
        run: |
          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://git@github.com/'
          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com:'
      # v16
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          name: veridise-public
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
      - name: 'Build with ${{ matrix.compiler.name }}'
        run: "nix --print-build-logs build '${{ matrix.compiler.derivation }}'"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "Test results (${{ matrix.compiler.name }})"
          path: "result/artifacts/${{ matrix.compiler.report }}"

  publish-tests:
    name: "Publish test results"
    needs: build
    runs-on: ubuntu-24.04
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: artifacts/**/*.xml
          comment_mode: failures
