name: Debug CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - uses: cachix/cachix-action@v15
        with:
          name: veridise-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Create directory where to store published summaries
        run: mkdir -p gh-artifacts
      - name: Build with GCC
        run: nix --print-build-logs build '.#debugGCC'
      - name: Copy xUnit report for GCC
        run: cp result/artifacts/gcc-report.xml gh-artifacts
      - name: Build with Clang
        run: nix --print-build-logs build '.#debugClangCov'
      - name: Copy xUnit and lcov reports for clang
        run: cp result/artifacts/clang-report.xml result/artifacts/report.lcov gh-artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: gh-artifacts/*-report.xml
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: gh-artifacts/*.lcov
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

