name: Sync or unsync a given GitHub Issue to Jira

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    name: Check for Jira configuration
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - id: check
        run: |
          if [ -n "${{ secrets.JIRA_BASE_URL }}" ] && \
             [ -n "${{ secrets.JIRA_USER_EMAIL }}" ] && \
             [ -n "${{ secrets.JIRA_API_TOKEN }}" ]; then
            echo "Jira configuration found, proceeding."
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "Jira configuration missing, will not proceed."
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi

  sync-issue:
    needs: check-secrets
    if: ${{ needs.check-secrets.outputs.proceed == 'true' && github.event.label.name == 'sync-to-jira' }}
    name: Sync or unsync GitHub Issue to Jira
    runs-on: ubuntu-latest
    permissions:
      issues: write # to add labels to issues
      contents: write # to create labels in the repository
    env:
      JIRA_BASE_URL: "${{ secrets.JIRA_BASE_URL }}"
      JIRA_USER_EMAIL: "${{ secrets.JIRA_USER_EMAIL }}"
      JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN }}"
      JIRA_PROJECT_KEY: "LLZK"

      GITHUB_API_URL: "${{ github.api_url }}"
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY_OWNER: "${{ github.repository_owner }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"

      ISSUE_NUM: "${{ github.event.issue.number }}"
      ACTION: "${{ github.event.action == 'labeled' && 'link' || 'unlink' }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Install python requirements
        run: |
          pip install --upgrade pip && pip install -r scripts/requirements.txt

      - name: Run driver script
        run: |
          python3 scripts/jira_driver.py --issue "$ISSUE_NUM" "$ACTION"
