name: Update docs on main
on:
  push:
    branches:
      main

jobs:
  call-deploy-github-pages:
    # No version specified for "latest" deployment
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
