name: Update GitHub Issue synced on Jira

on:
  issue_comment:
  issues:
    types: [closed, reopened, deleted]

jobs:
  sync-issue:
    if: ${{ secrets.JIRA_BASE_URL != '' && secrets.JIRA_USER_EMAIL != '' && secrets.JIRA_API_TOKEN != '' }}
    name: Update GitHub Issue to Jira
    runs-on: ubuntu-latest
    permissions:
      issues: read # All updates happen to Jira, so permissions can be read-only here
    env:
      JIRA_BASE_URL: "${{ secrets.JIRA_BASE_URL }}"
      JIRA_USER_EMAIL: "${{ secrets.JIRA_USER_EMAIL }}"
      JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN }}"
      JIRA_PROJECT_KEY: "LLZK"

      GITHUB_API_URL: "${{ github.api_url }}"
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY_OWNER: "${{ github.repository_owner }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"

      ISSUE_NUM: "${{ github.event.issue.number }}"
      UPDATE_SUMMARY: "Issue comment ${{ github.event.action }}: ${{ github.event.comment }}"
      ACTION: "${{ github.event.action }}"
    steps:
      - name: Check if issue is synced
        uses: actions/github-script@v7
        id: check_label
        with:
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            const hasLabel = labels.includes('sync-to-jira');
            core.setOutput('has-label', hasLabel);

      - name: Checkout repository
        if: steps.check_label.outputs.has-label == 'true'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python
        if: steps.check_label.outputs.has-label == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Install python requirements
        if: steps.check_label.outputs.has-label == 'true'
        run: |
          pip install --upgrade pip && pip install -r scripts/requirements.txt

      - name: Update issue
        if: steps.check_label.outputs.has-label == 'true' && ${{ github.event_name }} == "issue_comment"
        run: |
          python3 jira_driver.py --issue "$ISSUE_NUM" update --summary "$UPDATE_SUMMARY"

      - name: Transition issue status
        if: steps.check_label.outputs.has-label == 'true' && ${{ github.event_name }} == "issues"
        run: |
          python3 jira_driver.py --issue "$ISSUE_NUM" transition --action "$ACTION"
