name: Update docs on main
on:
  push:
    branches:
      main
      "iangneal/gh-pages-fix" # temporary test override

jobs:
  call-deploy-github-pages:
    # No version specified for "latest" deployment
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
